import AppKit
import GRDB

@MainActor @Observable
final class ExclusionManager {
    private(set) var excludedApps: [ExcludedApp] = []
    private let database: AppDatabase

    /// Concealed pasteboard types that indicate sensitive data
    private static let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.nspasteboard.TransientType",
        "org.nspasteboard.TransientType",
        "com.apple.is-transient",
    ]

    init(database: AppDatabase) {
        self.database = database
    }

    func loadExcludedApps() throws {
        excludedApps = try database.dbQueue.read { db in
            try ExcludedApp.fetchAll(db)
        }
    }

    func addExclusion(bundleId: String, appName: String) throws {
        let app = ExcludedApp(bundleId: bundleId, appName: appName)
        try database.dbQueue.write { db in
            try app.insert(db)
        }
        try loadExcludedApps()
    }

    func removeExclusion(bundleId: String) throws {
        _ = try database.dbQueue.write { db in
            try ExcludedApp.deleteOne(db, key: bundleId)
        }
        try loadExcludedApps()
    }

    func isExcluded(bundleId: String?) -> Bool {
        guard let bundleId else { return false }
        return excludedApps.contains { $0.bundleId == bundleId }
    }

    /// Check if pasteboard contains concealed/sensitive types
    static func containsConcealedContent(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        let typeStrings = Set(types.map(\.rawValue))
        return !typeStrings.isDisjoint(with: concealedTypes)
    }

    /// Get the frontmost application's bundle identifier
    static func frontmostAppBundleId() -> String? {
        NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    /// Get the frontmost application's name
    static func frontmostAppName() -> String? {
        NSWorkspace.shared.frontmostApplication?.localizedName
    }
}
